name: moti_mente
description: APP to create motivational phrases.

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^7.0.2
  google_fonts: ^4.0.4
  lottie: ^2.3.2
  flutter_animate: ^4.1.1+1
  dio: ^5.1.2
  flutter_bloc: ^8.1.3
  logger: ^1.3.0
  pretty_dio_logger: ^1.3.1
  firebase_core: ^2.13.0
  get_it: ^7.6.0
  flutter_svg: ^2.0.6
  share_plus: ^7.0.1
  path_provider: ^2.0.15
  supabase_flutter: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.4
  flutter_native_splash: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/
